#!/bin/bash

exec >inlined_mods.c

cat <<EOF
// do not edit this file
// this file is generated from inlined.mods
// please edit inlined.mods to inline modules into the limo binary

#include <stdio.h>
#include "limo.h"

EOF
for mod in $(cat inlined.mods | grep -v '^#'); do
    printf 'void limo_inline_init_%s(limo_data *);\n' "$mod"
done

cat <<EOF

struct INLINE_MODLIST_ITEM inline_mod_funs[] = {
EOF
for mod in $(cat inlined.mods | grep -v '^#'); do
    printf '{"%s", limo_inline_init_%s },\n' "$mod" "$mod"
done
printf '{NULL, NULL} };'

