#!/bin/bash

if which ncursesw6-config > /dev/null; then
    NCURSESFLAGS="$(ncursesw6-config --libs)"
else
    NCURSESFLAGS="$(pkg-config --libs ncurses)"
fi

echo "libs/ncurses/ncurses.a $NCURSESFLAGS"
